theme = "modus_vivendi"

[editor]
scrolloff = 8
cursorline = true
line-number = "relative"
bufferline = "multiple"
auto-save = { focus-lost = true }
auto-pairs = true

# Fast, contextual indenting and completion
[editor.smart-tab]
enable = true
supersede-menu = true

[editor.whitespace]
render = "none"

[editor.indent-guides]
render = false

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
# Kept clean, but includes diagnostic counter so you know errors exist without popups
right = ["diagnostics", "file-type", "position"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.search]
smart-case = true

[editor.lsp]
display-messages = false
display-inlay-hints = false

[keys.insert]
"C-[" = "normal_mode"

[keys.normal]
"C-s" = ":w"

"H" = ":buffer-previous"
"L" = ":buffer-next"
"A-w" = ":buffer-close"

"C-c" = "toggle_comments"
"X" = "extend_line_above"

"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"

[keys.select]
"C-c" = "toggle_comments"
